name: lua_lint

# Lint on lua changes on builtin or if workflow changed
on:
  push:
    paths:
      - 'builtin/**.lua'
      - 'games/devtest/**.lua'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'builtin/**.lua'
      - 'games/devtest/**.lua'
      - '.github/workflows/**.yml'

jobs:
  luacheck:
    name: "Builtin Luacheck and Unit Tests"
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3
    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1.5"
    - uses: leafo/gh-actions-luarocks@v4

    - name: Install LuaJIT
      run: |
        cd $HOME
        git clone https://github.com/LuaJIT/LuaJIT/
        cd LuaJIT
        make -j$(nproc)

    - name: Install luarocks tools
      run: |
        luarocks install --local luacheck
        luarocks install --local busted

    - name: Run checks (builtin)
      run: |
        $HOME/.luarocks/bin/luacheck builtin
        $HOME/.luarocks/bin/busted builtin
        $HOME/.luarocks/bin/busted builtin --lua=$HOME/LuaJIT/src/luajit

    - name: Run checks (devtest)
      run: |
        $HOME/.luarocks/bin/luacheck --config=games/devtest/.luacheckrc games/devtest
